global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "linux-node"
    static_configs:
      - targets: ["192.168.x.x:9100"]   # Example Linux laptop
      - targets: ["192.168.x.x:9100"]   # Example ProBook

  - job_name: "windows-node"
    static_configs:
      - targets: ["192.168.x.x:9182"]   # Example Windows PC
